services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
        - ./api/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
